<?php
return [
/*--------------------------------------------------*/
   "Langue" => "Langue",
/*--------------------------------------------------*/
   "Bouton_A" => "Accueil",
   "Bouton_T" => "Trouver un trajet",
   "Bouton_P" => "Proposer un trajet",
   "Bouton_M" => "Messagerie",
   "Bouton_S" => "Se connecter",
   "Trajet"=>"Mes trajets",
   "Se_deconnecter"=>"Se déconnecter",
   "Mon_compte"=>"Mon compte",
/*--------------------------------------------------*/
  "titre1" => "Partager votre trajet,", 
  "titre2" => "économiser et voyager ensemble !",
  "titre3" => "Trouver un conducteur ou un passager en quelques cliques",
/*--------------------------------------------------*/
  "bouton_rechercher" => "Rechercher un trajet",
  "bouton_proposer" => "Proposer un trajet"
/*--------------------------------------------------*/,
  "Placeholder_D" => "Ville de départ",
  "Placeholder_A" => "Ville d'arrivée",
  "bouton_recherche" => "Recherche",
  "Date"=>"jj-mm-aaaa",
/*--------------------------------------------------*/
  "Comment_ça_marche" => "Comment ça marche ?",
  "Publier" => "Publier votre trajet",
  "text1" => "Entrer votre départ, destination, date ",
  "text2" => "et le nombre de place",

  "Reserver" => "Réserver facilement",
  "text4" => "Choissiser un trajet selon",
  "text5" => "vos préferences",

  "text6" => "Voyager ensemble !",
  "text7"=> "Rencontrer, partager",
  "text8" =>"et économiser",
/*--------------------------------------------------*/
  "Pourquoi_nous_choisir" => "Pourquoi nous choisir ?",

  "Economique" =>"Economique",
  "Texte1"=>"Parteger les frais de trajets",

  "Ecologique" =>"Ecologique",
  "Texte2"=>"Reduisser votre empreinte carbonne",
  
  "Rencontre"=>"Rencontre",
  "Texte3"=> "Rencontrer des personnes près de chez vous",

  "Fiable"=>"	Fiable",
  "Texte4"=>"Profils vérifiés",
/*--------------------------------------------------*/
  "Fermer" => "Fermer",
/*--------------------------------------------------*/
  "CGU" => "Condition général d'utilisation",
/*--------------------------------------------------*/
  "Mot"=>"Mot de passe oublié ?",
  "Inscription"=>"S'inscrire",
  "Connecter" => "Se connecter",
  "Mot2"=>"Mot de passe",
  "identifiant"=>"Pseudo, adresse-mail ou numéro",
/*-------------------------------------------------*/
  "E_P"=>"Entrer votre prénom :",
  "E_N"=>"Entrer votre nom :",
  "P"=>"Prénom",
  "N"=>"Nom",
  "E_M"=>"Entrer votre mail :",
  "M"=>"E-mail",
  "E_PP"=>"Choisisser votre photo de profil :",
  "E_Tel"=>"Entrer votre numéro de téléphone :",
/*-------------------------------------------------*/
  "©"=>"© 2024 Drive Us. Tous droits réservés.",
/*-------------------------------------------------*/
  /* Pages supplémentaires */
  "my_account" => "Mon compte",
  "my_profile" => "Mon profil",
  "my_trips" => "Mes trajets",
  "my_reservations" => "Mes réservations",
  "received_reservations" => "Réservations reçues",
  "messaging" => "Messagerie",
  "find_trip" => "Trouver un trajet",
  "publish_trip" => "Publier un trajet",
  "logout" => "Se déconnecter",
  "login" => "Se connecter",
  "register" => "S'inscrire",
  "home" => "Accueil",
  /* Profil */
  "edit_profile" => "Modifier mon profil",
  "personal_info" => "Informations personnelles",
  "coordinates" => "Coordonnées",
  "payment" => "Moyen de paiement",
  "language" => "Langue",
  "save" => "Enregistrer",
  "first_name" => "Prénom",
  "last_name" => "Nom",
  "email" => "E-mail",
  "phone" => "Téléphone",
  "address" => "Adresse",
  "gender" => "Genre",
  "male" => "Homme",
  "female" => "Femme",
  "other" => "Autre",
  "date_of_birth" => "Date de naissance",
  "profile_photo" => "Photo de profil",
  "change_photo" => "Changer la photo",
  "rib" => "RIB",
  /* Trajets */
  "departure" => "Départ",
  "arrival" => "Destination",
  "date" => "Date",
  "time" => "Heure",
  "places" => "Places",
  "price" => "Prix",
  "available_places" => "Places disponibles",
  "meeting_point" => "Point de rencontre",
  "duration" => "Durée",
  "stops" => "Arrêts",
  "add_stop" => "Ajouter un arrêt",
  "preferences" => "Préférences",
  "luggage" => "Bagages",
  "smoking" => "Fumeur",
  "pets" => "Animaux",
  "children" => "Enfants autorisés",
  "min_age" => "Âge minimum",
  "max_age" => "Âge maximum",
  "yes" => "Oui",
  "no" => "Non",
  "small" => "Petit",
  "medium" => "Moyen",
  "large" => "Grand",
  "non_smoking" => "Non-fumeur",
  "publish" => "Publier",
  "cancel" => "Annuler",
  "delete" => "Supprimer",
  "edit" => "Modifier",
  /* Réservations */
  "reserve" => "Réserver",
  "reservation_confirmed" => "Réservation confirmée",
  "cancel_reservation" => "Annuler la réservation",
  "trip_details" => "Détails du trajet",
  "driver" => "Conducteur",
  "passenger" => "Passager",
  "rating" => "Note",
  "reviews" => "Avis",
  "contact_driver" => "Contacter le conducteur",
  "contact_passenger" => "Contacter le passager",
]
?>
