<?php
return [
/*--------------------------------------------------*/
   "Langue" => "language",
/*--------------------------------------------------*/
   "Bouton_A" => "Home",
   "Bouton_T" => "Find a trip",
   "Bouton_P" => "Suggest a trip",
   "Bouton_M" => "messaging service",
   "Bouton_S" => "Login",
   "Trajet"=>"My trips",
   "Se_deconnecter"=>"Log out",
   "Mon_compte"=>"My account",
/*--------------------------------------------------*/
  "titre1" => "Share your drive,", 
  "titre2" => "save and travel together !",
  "titre3" => "Find a driver or passenger in just a few clicks",
/*--------------------------------------------------*/
  "bouton_rechercher" => "Find a route",
  "bouton_proposer" => "Suggest a route"
/*--------------------------------------------------*/,
  "Placeholder_D" => "Departure city",
  "Placeholder_A" => "arrival city",
  "bouton_recherche" => "research",
  "Date"=>"dd-mm-yyyy",
/*--------------------------------------------------*/
  "Comment_ça_marche" => "How it work ?",
  "Publier" => "Publish your trip",
  "text1" => "Enter your departure time, destination, and date",
  "text2" => "and number of places",

  "Reserver" => "Book easily",
  "text4" => "Choose a route according to",
  "text5" => "your preferences",

  "text6" => "Travel together !",
  "text7"=> "Meet, share",
  "text8" =>"and save",

  "Pourquoi_nous_choisir" => "Why choose us ?",
  "Economique" =>"economical",
  "Texte1"=>"Share travel expenses",

  "Ecologique" =>"environmentally friendly",
  "Texte2"=>"Reduce your carbon footprint",
  
  "Rencontre"=>"Meet",
  "Texte3"=> "Meet people near you",

  "Fiable"=>"reliable",
  "Texte4"=>"Verified Profiles",
/*--------------------------------------------------*/
  "Fermer" => "Close",
/*--------------------------------------------------*/
  "CGU" => "general terms of use",
/*--------------------------------------------------*/
  "Mot"=>"Forgotten password ?",
  "Inscription"=>"Register",
  "Connecter" => "Login",
  "Mot2"=>"Password",
  "identifiant"=>"Pseudo, mail or phone",
/*-------------------------------------------------*/
  "©"=>"© 2024 Drive Us. All rights reserved.",
/*-------------------------------------------------*/
  /* Additional pages */
  "my_account" => "My account",
  "my_profile" => "My profile",
  "my_trips" => "My trips",
  "my_reservations" => "My reservations",
  "received_reservations" => "Received reservations",
  "messaging" => "Messaging",
  "find_trip" => "Find a trip",
  "publish_trip" => "Publish a trip",
  "logout" => "Log out",
  "login" => "Log in",
  "register" => "Sign up",
  "home" => "Home",
  /* Profile */
  "edit_profile" => "Edit my profile",
  "personal_info" => "Personal information",
  "coordinates" => "Contact details",
  "payment" => "Payment method",
  "language" => "Language",
  "save" => "Save",
  "first_name" => "First name",
  "last_name" => "Last name",
  "email" => "Email",
  "phone" => "Phone",
  "address" => "Address",
  "gender" => "Gender",
  "male" => "Male",
  "female" => "Female",
  "other" => "Other",
  "date_of_birth" => "Date of birth",
  "profile_photo" => "Profile photo",
  "change_photo" => "Change photo",
  "rib" => "RIB",
  /* Trips */
  "departure" => "Departure",
  "arrival" => "Destination",
  "date" => "Date",
  "time" => "Time",
  "places" => "Seats",
  "price" => "Price",
  "available_places" => "Available seats",
  "meeting_point" => "Meeting point",
  "duration" => "Duration",
  "stops" => "Stops",
  "add_stop" => "Add a stop",
  "preferences" => "Preferences",
  "luggage" => "Luggage",
  "smoking" => "Smoking",
  "pets" => "Pets",
  "children" => "Children allowed",
  "min_age" => "Minimum age",
  "max_age" => "Maximum age",
  "yes" => "Yes",
  "no" => "No",
  "small" => "Small",
  "medium" => "Medium",
  "large" => "Large",
  "non_smoking" => "Non-smoking",
  "publish" => "Publish",
  "cancel" => "Cancel",
  "delete" => "Delete",
  "edit" => "Edit",
  /* Reservations */
  "reserve" => "Book",
  "reservation_confirmed" => "Booking confirmed",
  "cancel_reservation" => "Cancel booking",
  "trip_details" => "Trip details",
  "driver" => "Driver",
  "passenger" => "Passenger",
  "rating" => "Rating",
  "reviews" => "Reviews",
  "contact_driver" => "Contact the driver",
  "contact_passenger" => "Contact the passenger",
];
?>
