; SMTP configuration for Ionos (fill with your credentials)
MAIL_HOST=smtp.ionos.fr
MAIL_PORT=465
MAIL_SMTP_SECURE=ssl
MAIL_USER=noreply@driveus.eu
MAIL_PASS=codeandcofee
MAIL_FROM_NAME=DriveUs
MAIL_DEBUG=0
